services:
  - type: web
    name: resumeforge-ml
    env: python
    rootDir: ml_service
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: resumeforge-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: ML_SERVICE_URL
        sync: false
